"""
TikTok checker.
Edit USERNAME / POST below, then run: python tiktok.py

Both profile and video pages embed a "statusCode" field in their
rehydration JSON (0 = loaded fine, nonzero = not found/unavailable) -
that's more reliable than status codes or text search, since TikTok's
shell HTML is otherwise identical (and even contains generic "couldn't
find this account" boilerplate) regardless of whether the target exists.

get_comments() and get_hashtag_data() are included for interface
consistency but return None/found=None: TikTok's comment API requires
signed anti-bot tokens (msToken, X-Bogus) that only its obfuscated
client-side JS can generate, and hashtag pages no longer server-render
real stats - see each function's docstring for details.
"""
import json
import re
import sys

import requests

USERNAME = "target_username"
POST = "https://www.tiktok.com/@target_username/video/0000000000000000000"


DEFAULT_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
}


def _get(url, headers=None, timeout=10, allow_redirects=True):
    merged = dict(DEFAULT_HEADERS)
    if headers:
        merged.update(headers)
    try:
        return requests.get(url, headers=merged, timeout=timeout, allow_redirects=allow_redirects)
    except requests.RequestException as exc:
        print(f"[!] Request failed for {url}: {exc}", file=sys.stderr)
        return None


def _show(label, value):
    if isinstance(value, (dict, list)):
        print(f"{label}:\n{json.dumps(value, indent=2, default=str)}")
    else:
        print(f"{label}: {value}")


def _status_code(text):
    match = re.search(r'"statusCode":(-?\d+)', text)
    return match.group(1) if match else None


def get_profile_data(username):
    profile_url = f"https://www.tiktok.com/@{username}"
    resp = _get(profile_url)
    result = {"platform": "TikTok", "username": username, "url": profile_url, "exists": None}
    if resp is None:
        result["error"] = "request error"
        return result
    if resp.status_code != 200:
        result["error"] = f"HTTP {resp.status_code}"
        return result

    text = resp.text
    status = _status_code(text)
    if status != "0":
        result["exists"] = False
        return result

    result["exists"] = True
    for field in ("followerCount", "followingCount", "heartCount", "videoCount"):
        m = re.search(rf'"{field}":(\d+)', text)
        result[field] = int(m.group(1)) if m else None
    return result


def get_post_data(post):
    resp = _get(post)
    result = {"platform": "TikTok", "post": post, "found": None}
    if resp is None:
        result["error"] = "request error"
        return result
    if resp.status_code != 200:
        result["error"] = f"HTTP {resp.status_code}"
        return result

    text = resp.text
    if _status_code(text) != "0":
        result["found"] = False
        return result

    result["found"] = True
    desc = re.search(r'"desc":"((?:[^"\\]|\\.)*)"', text)
    result["description"] = desc.group(1) if desc else None
    for field in ("playCount", "diggCount", "commentCount", "shareCount", "collectCount"):
        m = re.search(rf'"{field}":(\d+)', text)
        result[field] = int(m.group(1)) if m else None
    return result


def get_views(post):
    data = get_post_data(post)
    return data.get("playCount") if data.get("found") else None


def get_likers(post):
    # TikTok has never exposed a public, unauthenticated list of who liked a video.
    return None


def get_comments(post, count=20):
    # TikTok's comment-list API (api/comment/list) rejects plain requests with
    # status_code 5 - it requires signed anti-bot params (msToken, X-Bogus)
    # generated by TikTok's obfuscated client-side JS, which isn't something
    # a plain HTTP request can produce. No public, unauthenticated path exists.
    return None


def get_hashtag_data(hashtag):
    # TikTok's hashtag/challenge pages no longer server-render real stats
    # (view/video counts) into the raw HTML - like profile pages used to,
    # this content is now fetched client-side after load. No reliable
    # unauthenticated signal is available.
    return {
        "platform": "TikTok", "hashtag": hashtag, "found": None,
        "error": "TikTok no longer serves hashtag stats to logged-out requests",
    }


if __name__ == "__main__":
    _show("profile", get_profile_data(USERNAME))
    _show("post", get_post_data(POST))
    _show("views", get_views(POST))
    _show("likers", get_likers(POST))
    _show("comments", get_comments(POST))
    _show("hashtag", get_hashtag_data("foryoupage"))
